const tableFackeData = [
  {
    id: 1,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 2,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 3,
    renderin: "Gecko",
    browser: "Camino",
    platform: "Commodore 64",
    engine: "1.7",
    css: "A",
  },
  {
    id: 4,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 5,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 6,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 7,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.4",
    css: "A",
  },
  {
    id: 8,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 9,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "Win 98+/OSX.2+",
    engine: "1.7",
    css: "A",
  },
  {
    id: 10,
    renderin: "Gecko",
    browser: "Firefox 1.0",
    platform: "OSX.2+",
    engine: "1.8",
    css: "b",
  },
];


export default tableFackeData;